# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'







  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  target 'double' do
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '10.0'
	pod 'Alamofire', '~> 4.3'
	pod 'SWXMLHash', '~> 3.0.0'
  end

    # Pods for library

  # Pods for double

